sudo: required
services:
  - docker
language: python
python:
  - "3.6"
install:
  - pip install -U pip
  - pip install tox
  - pip freeze
script:
  - tox

stages:
  - lint
  - test
  - docker-build
  - name: release
    if: tag IS present

jobs:
  include:
    - env: TOXENV=py36

    - stage: lint
      env: TOXENV=lint

    - stage: docker-build
      env: TOXENV=docker-build ARCH=aarch64
    - stage: docker-build
      env: TOXENV=docker-build ARCH=i386
    - stage: docker-build
      env: TOXENV=docker-build ARCH=amd64
    - stage: docker-build
      env: TOXENV=docker-build ARCH=armhf
    - stage: docker-build
      env: TOXENV=docker-build ARCH=armv7
      
    - stage: release
      env: TOXENV=docker-build ARCH=aarch64
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u ${DOCKER_USERNAME} --password-stdin
        - bash scripts/docker-push.sh ${TRAVIS_BUILD_DIR}
    - stage: release
      env: TOXENV=docker-build ARCH=i386
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u ${DOCKER_USERNAME} --password-stdin
        - bash scripts/docker-push.sh ${TRAVIS_BUILD_DIR}
    - stage: release
      env: TOXENV=docker-build ARCH=amd64
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u ${DOCKER_USERNAME} --password-stdin
        - bash scripts/docker-push.sh ${TRAVIS_BUILD_DIR}
    - stage: release
      env: TOXENV=docker-build ARCH=armhf
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u ${DOCKER_USERNAME} --password-stdin
        - bash scripts/docker-push.sh ${TRAVIS_BUILD_DIR}
    - stage: release
      env: TOXENV=docker-build ARCH=armv7
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u ${DOCKER_USERNAME} --password-stdin
        - bash scripts/docker-push.sh ${TRAVIS_BUILD_DIR}
