sudo: required
services:
  - docker
language: python
python:
  - "3.6"
env:
  - TOXENV=py36
  - TOXENV=lint
  - TOXENV=docker-build ARCH=aarch64
  - TOXENV=docker-build ARCH=i386
  - TOXENV=docker-build ARCH=amd64
  - TOXENV=docker-build ARCH=armhf
install:
  - pip install -U pip
  - pip install tox
  - pip freeze
script:
  - tox
